### ISSUE TITLE
Icons not consistent based on selected Role(s)

### ISSUE THREAD

**Issue by brownhoward** [SolidOS/solid-panes#173] opened 2019-09-06 16:39 UTC
The icons/buttons displayed when the various combinations of user Roles are selected under Preferences:
1. Normal (neither Developer or Power User selected)
2. Developer only
3. Power User only
4. Both Developer and Power User

My assumption is that if you select Developer, Power User or both, you should still get the icons/buttons available as a Normal user. But that does not appear to be the case.

Attached is a PDF showing the icons/buttons displayed for each Role combination at:
1. Top of the Data Browser (not sure what this toolbar is called).
2. When a Folder is selected.
3. When the green plus button is pressed.

[Data-Browser-Icons.pdf](https://github.com/solid/solid-panes/files/3584812/Data-Browser-Icons.pdf)

In the PDF, the yellow cells show the icons/buttons currently displayed in each context menu for each Role. The red cells are the places where I believe icons/buttons are missing.

**Comment by megoth** [comment] 2019-09-16 16:41
Based on the red fields in [Data-Browser-Icons.pdf](file:///Users/arnehassel/Projects/solid/data-browser-docs/docs/images/Data-Browser-Icons.pdf):

- Unable to reproduce missing Long Chat for normal users
- Meeting Pane is a Power User pane (ie red fields are wrong)
- Notepad Pane is a Power User pane (so strange if you were able to create new Notepad as a normal user - unable to reproduce it myself)
- Scheduled Event Pane is a Power User pane (ie red fields are wrong)
- Slideshow Pane is a Power User pane (strange that it didn't show up for Power User, but did so for Power User + Developer - unable to reproduce it myself)
- Under the Hood is only a Developer pane for now - will be like this until we've figured out how we want to express OR-relations in the audience-property

@kevin-howard-jd we need to look at this together, but based on my findings, this is in fact working as intended.

**Comment by megoth** [comment] 2019-09-24 10:40
Closing this issue as it is not a bug per ce, but rather some confusion about which views belong to which user type. Something that we probably will see more of, so at some point [we might want to look at other ways of signaling to the data browser which views people will want to use](https://forum.solidproject.org/t/introducing-user-types-developer-and-power-user-in-the-solid-data-browser/2204/6?u=megoth).

**Closed as completed by megoth** 2019-09-24 10:40 UTC
Labels: bug
